cd .\break_09\ 
python break_test.py
cd ..
cd .\break_10\ 
python break_test.py
cd ..
cd .\break_11\ 
python break_test.py
cd ..
cd .\break_12\ 
python break_test.py
cd ..
cd .\break_13\ 
python break_test.py
cd ..
cd .\break_14\ 
python break_test.py
cd ..
cd .\break_15\ 
python brea_test.py